//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Service\\Stora" +
            "ge\\AccountsDataBase.mdf;Integrated Security=True")]
        public string AccountsDataBaseConnectionString {
            get {
                return ((string)(this["AccountsDataBaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\USER\\DOWNLOADS\\AUBTIM" +
            "EMANAGEMENTAPP\\AUBTIMEMANAGEMENTAPP\\SERVER\\SERVICE\\STORAGE\\ACCOUNTSDATABASE.MDF;" +
            "Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate" +
            "=False")]
        public string C__USERS_USER_DOWNLOADS_AUBTIMEMANAGEMENTAPP_AUBTIMEMANAGEMENTAPP_SERVER_SERVICE_STORAGE_ACCOUNTSDATABASE_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_USER_DOWNLOADS_AUBTIMEMANAGEMENTAPP_AUBTIMEMANAGEMENTAPP_SERVER_SERVICE_" +
                    "STORAGE_ACCOUNTSDATABASE_MDFConnectionString"]));
            }
        }
    }
}
